services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring_network
    labels:
      "com.helios.target": "http://localhost:9090"
  node-exporter:
    image: prom/node-exporter
    command:
      - '--web.config.file=/etc/node_exporter/config.yml'
    volumes:
      - ./config.yml:/etc/node_exporter/config.yml
    networks:
      - monitoring_network
    ports:
      - 9100:9100
    labels:
      "com.helios.target": "http://localhost:9100"
  alert-manager:
    image: prom/alertmanager
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - monitoring_network
    ports:
      - 9093:9093
    labels:
      "com.helios.target": "http://localhost:9093"

volumes:
  prometheus_data:

networks:
  monitoring_network:
    driver: bridge
