 services:
  redis:
    restart: always
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    labels:
      "com.helios.target": "http://localhost:8082"

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis:6379
    ports:
      - '8001:8001'
    labels:
      "com.helios.target": "http://localhost:8001"